### ISSUE TITLE
No se puede escribir en linea de comandos..

### ISSUE THREAD

**Issue by hessedelohim** [hugoruscitti/lanas#17]
al escribir el comando "pilas.iniciar()", cuando se vuelve a la ventana del lanas, no permite escribir, tampoco aparece el cursor..

**Comment by hugoruscitti** [comment]
Lo pude reproducir acá, es un bug de pilas, lo cargué ahí, y en cuanto lo resuelva aviso
por acá.

Para mas referencias ver el bug dentro de pilas.

https://github.com/hugoruscitti/pilas/issues/64

**Comment by hugoruscitti** [comment]
Ahí lo pude solucionar dentro de pilas:

https://github.com/hugoruscitti/pilas/issues/64

¿Vos estás usando lanas dentro del asistente de pilas o directamente ejecutando lanas desde consola?

**Comment by hessedelohim** [comment]
ejecuto lanas directamente desde consola.. y de ahi abro el pilas.. [ pilas.iniciar() ]

**Comment by hugoruscitti** [comment]
Ahí lo resolví en el issue #4, ahora se puede abrir lanas desde consola y luego escribir pilas.iniciar(). La pantalla de pilas aparece como una ventana independiente.
