### ISSUE TITLE
[Funcionalidad] Sentencias multilínea.

### ISSUE THREAD

**Issue by binary-sequence** [hugoruscitti/lanas#19]
Lanas no permite sentencias multilínea (útil para declaración de listas, tuplas, diccionarios, etc)

```
lista = [
    1,
    2,]
```

Relacionado con pilas: https://github.com/hugoruscitti/pilas/issues/138

**Comment by hugoruscitti** [comment]
Va quedando mejor, igual me parece que es un fix parcial, me gustaría revisarlo mas tarde
para ver si puedo contemplar mas casos multilinea:

![Instant nea 13:01:13 11:56-2](https://f.cloud.github.com/assets/99183/62890/d0251f7c-5d91-11e2-88cd-a8b13d7024c7.png)
