### ISSUE TITLE
Clarification about license

### ISSUE THREAD

**Issue by echevemaster** [hugoruscitti/lanas#24]
Hi,  what is the license of lanas, I'm packaging pilas engine for fedora, and I can't bundle it because it is separated project of main upstream, so, I have to package too. But, still I need at least a license file or a clarification about the license, Thanks for advance.

**Comment by hugoruscitti** [comment]
Hi @echevemaster !!!, we are working in a new pilas-engine version [1], that includes lanas with some fixes, can you consider that version of pilas-engine instead this repo?

https://github.com/hugoruscitti/python-pilas-experimental

**Comment by echevemaster** [comment]
Hi @hugoruscitti
Thanks for your prompt response.

Yeah, I can do. but I have two questions.

1.- You think you can release this new version, soon, I mean a release candidate? I'm asking because the fedora users  that I known that uses pilas (and the reason because I want package the software) are users of the stable version. I can't package it in fedora as python-pilas-experiment,  having a stable version in upstream at least that this be a total bifurcation of the project. 

2.- In case that this development it  is still raw, I can use the same license of pilas for lanas? or it is different.  

Many of this people are using pilas along with icaro.

**Comment by hugoruscitti** [comment]
Hi @echevemaster !!!, i plan to release the new version in the next week, i want to move
the code in python-pilas-experimental repo to the main repo (hugoruscitti/pilas).

I'm talking with Valentin Basel (creator of icaro) to test and integrate icaro in the new version.

**Comment by hugoruscitti** [comment]
Hi @echevemaster i have done the migration for the new version of pilas-engine: 

https://github.com/hugoruscitti/pilas

lanas it's now included in pilas and have the same license.
